### ISSUE TITLE
"Merged course options" form - Some of the fields are hidden by default

### ISSUE THREAD

**Issue by acquaalta** [LafColITS/moodle-local_course_merge#17]
Hi,
Some of the "Merged course options" form fields are hidden by default, and the user has to click the "Show more" link in order to expose them. To the best of knowledge, in previous versions all the fields in the form were shown by default.

Since we use almost all the fields in the "Merged course options" form, we always click the "Show more" link.

I know this is probably a feature and not bug. However, could you please create a site setting for the plugin that would enable the admin to determine if by default all the fields are shown or not?

![image](https://user-images.githubusercontent.com/51836675/73436886-01848f80-4354-11ea-9c6c-ce56c5b7f6d4.png)

**Comment by mackensen** [comment]
Hi @acquaalta; you're correct, this was added in the May 2019 release (see #1). It's desired behavior, based on the use case of faculty using the tool with the course names prepopulated and unchangeable, but I can see how this adds some steps if you're always setting those values. We can certainly look into making that configurable at the site level.

**Comment by acquaalta** [comment]
Thanks a lot for the quick and response and for your willingness to implement my suggestion :-)

**Comment by andyzito** [comment]
Hi @acquaalta, the latest release (3.6.3) contains a new plugin setting field, which is a list of the identifiers for the fields that are currently marked as advanced in the course creation form. To have one (or more) of the fields NOT be displayed as advanced, simply remove the corresponding identifier(s) from the textarea.

**Comment by acquaalta** [comment]
Hi Andrew,
Thanks a lot for the update of the plugin, and also for updating me about it ;-)
