### ISSUE TITLE
The following courses cannot be merged with this course:

### ISSUE THREAD

**Issue by yakarsu** [LafColITS/moodle-local_course_merge#18]
Hello

I have two diffrent courses but i didnt merge

Course 1 ID: FTV519-S01-2019.2 Film Language and Criticism

Course 2 ID: RC204-S01-2019.2 Film Language and Criticism

Thanks for help

**Comment by mackensen** [comment]
Hi @yakarsu, please see https://github.com/LafColITS/moodle-local_course_merge#category-depth; it sounds like the courses are too "far away" from each in category terms to be merged.
